version: '3.8'

services:
    nginx:
        restart: unless-stopped
        build:
            context: .
            dockerfile: ./docker/nginx/Dockerfile
            args:
                REACT_APP_API_ORIGIN: ${REACT_APP_API_ORIGIN}
                NODE_ENV: ${NODE_ENV}
        ports:
            - 80:80
        volumes:
            - "./docker/nginx/development:/etc/nginx/conf.d"
            - "static_volume:/app/django_static"

        depends_on:
            - api
    api:
        restart: unless-stopped
        environment:
          - SECRET_KEY=$SECRET_KEY
          - DEBUG=$DEBUG
          - EMAIL_HOST_USER=$EMAIL_HOST_USER
          - EMAIL_HOST_PASSWORD=$EMAIL_HOST_PASSWORD
          - DEFAULT_FROM_EMAIL=$DEFAULT_FROM_EMAIL
          - DATABASE_NAME=$DATABASE_NAME
          - DATABASE_USER=$DATABASE_USER
          - DATABASE_PASSWORD=$DATABASE_PASSWORD
          - SENTRY_DSN=$SENTRY_DSN
          - SENTRY_TRACES_SAMPLE_RATE=$SENTRY_TRACES_SAMPLE_RATE
          - USE_S3=$USE_S3
          - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
          - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
          - AWS_STORAGE_BUCKET_NAME=$AWS_STORAGE_BUCKET_NAME
        build:
            context: .
            dockerfile: ./docker/api/Dockerfile
        # ports:
        #     - 8000:8000
        volumes:
            - "static_volume:/app/django_static"
        depends_on:
            - db
        expose:
            - 8000
    db:
      restart: always
      image: postgres:latest
      volumes:
        - postgres_volume:/var/lib/postgresql/data/
      ports:
        - 5432:5432
      environment:
        - POSTGRES_DB=$DATABASE_NAME
        - POSTGRES_USER=$DATABASE_USER
        - POSTGRES_PASSWORD=$DATABASE_PASSWORD

volumes:
    static_volume: {}
    postgres_volume:

# - "static_volume:/app/django_static"
#             - "./api:/app/"
#             - "./front:/app/"
